from tkinter import *
from arquivoteste import horario
import string
def B_teste():
    master=Tk()
    v=open('testeB.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=1)
    mainloop()
    return mainloop()
def C_teste():
    master=Tk()
    v=open('testeC.txt')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=0)
    scrollbar = Scrollbar(master)
    scrollbar.pack(side=RIGHT, fill=Y)
    return mainloop()
def teste1():
    master=Tk()
    v=open('teste.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=0)
    mainloop()
    return mainloop()
def G_teste():
    master=Tk()
    v=open('testeG.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=1)
    mainloop()
    return mainloop()
def H_teste():
    master=Tk()
    v=open('testeH.txt','r')
    texto=v.read()
    print(texto)
    Message(master, text=texto).grid(row=1)
    mainloop()
    return mainloop()
def J_teste():
    master=Tk()
    v=open('testeJ.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=1)
    mainloop()
    return mainloop()
def L_teste():
    master=Tk()
    v=open('testeL.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=1)
    mainloop()
    return mainloop()
def M_teste():
    master=Tk()
    v=open('testeM.txt','r')
    texto=v.read()
    print(texto)
    Message(master,text=texto).grid(row=1)
    mainloop()
    return mainloop()
def N_teste():
    master=Tk()
    v=open('testeN.txt','r')
    texto=v.read()
    print(texto)
    Message(master, text=texto).grid(row=1)
    mainloop()
    return mainloop()
def teste_P():
    master=Tk()
    v=open('testeP.txt','r')
    texto=v.read()
    print(texto)
    Message(master, text=texto).grid(row=1)
    mainloop()
    return mainloop()
master=Tk()
Label(master,text='Trampolim da vitoria').grid(row=0)
Button(master, text='C', command=C_teste).grid(row=3, column=0, sticky=W, pady=5)
Button(master, text='G', command=G_teste).grid(row=4, column=0, sticky=W, pady=4)
Button(master,text='B',command=B_teste).grid(row=2,column=0,sticky=W,pady=4)
Button(master,text='A',command=teste1).grid(row=1,column=0,sticky=W,pady=4)
Button(master,text='H',command=H_teste).grid(row=5,column=0,sticky=W,pady=4)
Button(master,text='J',command=J_teste).grid(row=6,column=0,sticky=W,pady=4)
Button(master,text='L',command=L_teste).grid(row=7,column=0,sticky=W,pady=4)
Button(master,text='M',command=M_teste).grid(row=8,column=0,sticky=W,pady=4)
Button(master,text='N',command=N_teste).grid(row=9,column=0,sticky=W,pady=4)
Button(master,text='P',command=teste_P).grid(row=10,column=0,sticky=W,pady=4)
mainloop()


